# .github/workflows/chromatic.yml

# Workflow name
name: 'Release'

# Event for the workflow
on:
  push:
    branches: release

# List of jobs
jobs:
  build_and_test:
    # Operating System
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v2
        with:
          node-version: '12.13.1'
      - name: Install dependencies
        run: yarn
      - name: Build
        run: yarn build:package
      - name: Pack
        run: npm pack
      - name: Release
        uses: actions/upload-artifact@v2
        with:
          name: ds-components
          path: dao-storybook-*.tgz